name: Build and Deploy Windows Container App to Azure App Service

# Trigger the build on commits into the master branch
on:
  push:
    branches:
      - master
  workflow_dispatch:

# Starts jobs and sets the type of runner (Windows) they will run on.
jobs:
  build-and-deploy-to-azure:
    runs-on: windows-latest
    
    steps:
      
    # Check out the repository so your workflow can access it
    - uses: actions/checkout@v1
               
    # Authenticate a Service Principal to deploy to your Web App
    
      
        
        
        
    # Build and push the image to Azure Container Registry
    - name: Build and Push container to ACR
      run: |
        docker build taskapp/taskapp/
        
        
    # Deploy your container to App Service
    #- name: Deploy Container to Azure App Service
     # uses: azure/webapps-container-deploy@v1
      #with:
       # app-name: ${{ secrets.APP_NAME }}
        #images: ${{ secrets.REGISTRY_USERNAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:${{ github.sha }}

        
        
        
    
      # **** UNCOMMENT IF USING DOCKER HUB **** 
    # Use docker login
    #- name: Docker login to ACR
    #  uses: azure/docker-login@v1
    #  with:
    #    username: ${{ secrets.DOCKERHUB_USERNAME }}
    #    password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    # Build and push your image to Docker Hub
    #- name: Build and Push container to Docker Hub
    #  run: |
    #    docker build -t ${{ secrets.DOCKERHUB_REGISTRY_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }} taskapp/taskapp/
    #    docker push ${{ secrets.DOCKERHUB_REGISTRY_NAME }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}  
  
    # Deploy your container to App Service
    #- name: Deploy Container to Azure App Service
    #  uses: azure/webapps-container-deploy@v1
    #  with:
    #    app-name: ${{ secrets.APP_NAME }}
    #    images: ${{ secrets.DOCKERHUB_REGISTRY_NAME }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
  # *************************************** 
    
    
    # Deploy a dacpac file to a provisioned SQL server
    
      
      
        
        
